In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
Weather = pd.read_csv("weatherAUS.csv")

In [5]:
Weather

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  \
0       2008-12-01   Albury     13.4     22.9       0.6          NaN   
1       2008-12-02   Albury      7.4     25.1       0.0          NaN   
2       2008-12-03   Albury     12.9     25.7       0.0          NaN   
3       2008-12-04   Albury      9.2     28.0       0.0          NaN   
4       2008-12-05   Albury     17.5     32.3       1.0          NaN   
...            ...      ...      ...      ...       ...          ...   
145455  2017-06-21    Uluru      2.8     23.4       0.0          NaN   
145456  2017-06-22    Uluru      3.6     25.3       0.0          NaN   
145457  2017-06-23    Uluru      5.4     26.9       0.0          NaN   
145458  2017-06-24    Uluru      7.8     27.0       0.0          NaN   
145459  2017-06-25    Uluru     14.9      NaN       0.0          NaN   

        Sunshine WindGustDir  WindGustSpeed WindDir9am  ... Humidity9am  \
0            NaN           W           44.0          W  ...        71.0   
1            NaN         WNW           44.0        NNW  ...        44.0   
2            NaN         WSW           46.0          W  ...        38.0   
3            NaN          NE           24.0         SE  ...        45.0   
4            NaN           W           41.0        ENE  ...        82.0   
...          ...         ...            ...        ...  ...         ...   
145455       NaN           E           31.0         SE  ...        51.0   
145456       NaN         NNW           22.0         SE  ...        56.0   
145457       NaN           N           37.0         SE  ...        53.0   
145458       NaN          SE           28.0        SSE  ...        51.0   
145459       NaN         NaN            NaN        ESE  ...        62.0   

        Humidity3pm  Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  \
0              22.0       1007.7       1007.1       8.0       NaN     16.9   
1              25.0       1010.6       1007.8       NaN       NaN     17.2   
2              30.0       1007.6       1008.7       NaN       2.0     21.0   
3              16.0       1017.6       1012.8       NaN       NaN     18.1   
4              33.0       1010.8       1006.0       7.0       8.0     17.8   
...             ...          ...          ...       ...       ...      ...   
145455         24.0       1024.6       1020.3       NaN       NaN     10.1   
145456         21.0       1023.5       1019.1       NaN       NaN     10.9   
145457         24.0       1021.0       1016.8       NaN       NaN     12.5   
145458         24.0       1019.4       1016.5       3.0       2.0     15.1   
145459         36.0       1020.2       1017.9       8.0       8.0     15.0   

        Temp3pm  RainToday  RainTomorrow  
0          21.8         No            No  
1          24.3         No            No  
2          23.2         No            No  
3          26.5         No            No  
4          29.7         No            No  
...         ...        ...           ...  
145455     22.4         No            No  
145456     24.5         No            No  
145457     26.1         No            No  
145458     26.0         No            No  
145459     20.9         No           NaN  

[145460 rows x 23 columns]

In [7]:
Weather.isnull().sum()

Date                 0
Location             0
MinTemp           1485
MaxTemp           1261
Rainfall          3261
Evaporation      62790
Sunshine         69835
WindGustDir      10326
WindGustSpeed    10263
WindDir9am       10566
WindDir3pm        4228
WindSpeed9am      1767
WindSpeed3pm      3062
Humidity9am       2654
Humidity3pm       4507
Pressure9am      15065
Pressure3pm      15028
Cloud9am         55888
Cloud3pm         59358
Temp9am           1767
Temp3pm           3609
RainToday         3261
RainTomorrow      3267
dtype: int64

In [9]:
Weather.columns

Index(['Date', 'Location', 'MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation',
       'Sunshine', 'WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm',
       'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am',
       'Temp3pm', 'RainToday', 'RainTomorrow'],
      dtype='object')

In [11]:
Weather.shape

(145460, 23)

In [13]:
Weather.isnull().any(axis=1)

0         True
1         True
2         True
3         True
4         True
          ... 
145455    True
145456    True
145457    True
145458    True
145459    True
Length: 145460, dtype: bool

In [ ]:
Weather.info()

In [27]:
# Weather['Location'].fillna(Weather['Location'].mode(), inplace=True)
# Weather['WindGustDir'].fillna(Weather['WindGustDir'].mode(), inplace=True)
# mode = Weather['WindDir9am','WindDir3pm'].mode()

# mode1 = Weather['WindGustDir'].mode()
# print(mode)
# print(mode1)

Weather.drop(columns=['Date'], axis=1, inplace=True)
Weather

Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0              2     13.4     22.9       0.6          4.0       0.0   
1              2      7.4     25.1       0.0          NaN       NaN   
2              2     12.9     25.7       0.0          NaN       NaN   
3              2      9.2     28.0       0.0          NaN       NaN   
4              2     17.5     32.3       1.0          NaN       NaN   
...          ...      ...      ...       ...          ...       ...   
145455        41      2.8     23.4       0.0          NaN       NaN   
145456        41      3.6     25.3       0.0          NaN       NaN   
145457        41      5.4     26.9       0.0          NaN       NaN   
145458        41      7.8     27.0       0.0          NaN       NaN   
145459        41     14.9      NaN       0.0          NaN       NaN   

        WindGustDir  WindGustSpeed  WindDir9am  WindDir3pm  ...  Humidity9am  \
0                13           44.0          13          14  ...         71.0   
1                14           44.0           6          15  ...         44.0   
2                15           46.0          13          15  ...         38.0   
3                 4           24.0           9           0  ...         45.0   
4                13           41.0           1           7  ...         82.0   
...             ...            ...         ...         ...  ...          ...   
145455            0           31.0           9           1  ...         51.0   
145456            6           22.0           9           3  ...         56.0   
145457            3           37.0           9          14  ...         53.0   
145458            9           28.0          10           3  ...         51.0   
145459           16            NaN           2           2  ...         62.0   

        Humidity3pm  Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  \
0              22.0       1007.7       1007.1       8.0       7.0     16.9   
1              25.0       1010.6       1007.8       NaN       NaN     17.2   
2              30.0       1007.6       1008.7       NaN       2.0     21.0   
3              16.0       1017.6       1012.8       NaN       NaN     18.1   
4              33.0       1010.8       1006.0       7.0       8.0     17.8   
...             ...          ...          ...       ...       ...      ...   
145455         24.0       1024.6       1020.3       NaN       NaN     10.1   
145456         21.0       1023.5       1019.1       NaN       NaN     10.9   
145457         24.0       1021.0       1016.8       NaN       NaN     12.5   
145458         24.0       1019.4       1016.5       3.0       2.0     15.1   
145459         36.0       1020.2       1017.9       8.0       8.0     15.0   

        Temp3pm  RainToday  RainTomorrow  
0          21.8          0             0  
1          24.3          0             0  
2          23.2          0             0  
3          26.5          0             0  
4          29.7          0             0  
...         ...        ...           ...  
145455     22.4          0             0  
145456     24.5          0             0  
145457     26.1          0             0  
145458     26.0          0             0  
145459     20.9          0             2  

[145460 rows x 22 columns]

In [29]:
from sklearn.preprocessing import LabelEncoder
ln = LabelEncoder()
Weather[['Location','WindDir9am', 'WindDir3pm', 'RainToday', 'RainTomorrow', 'WindGustDir']] = Weather[['Location', 'WindDir9am', 'WindDir3pm', 'RainToday', 'RainTomorrow', 'WindGustDir']].apply(ln.fit_transform)

In [31]:
Weather.fillna(Weather.mode(), inplace=True)
Weather.fillna(Weather.median(), inplace=True)

In [33]:
Weather

Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0              2     13.4     22.9       0.6          4.0       0.0   
1              2      7.4     25.1       0.0          4.8       8.4   
2              2     12.9     25.7       0.0          4.8       8.4   
3              2      9.2     28.0       0.0          4.8       8.4   
4              2     17.5     32.3       1.0          4.8       8.4   
...          ...      ...      ...       ...          ...       ...   
145455        41      2.8     23.4       0.0          4.8       8.4   
145456        41      3.6     25.3       0.0          4.8       8.4   
145457        41      5.4     26.9       0.0          4.8       8.4   
145458        41      7.8     27.0       0.0          4.8       8.4   
145459        41     14.9     22.6       0.0          4.8       8.4   

        WindGustDir  WindGustSpeed  WindDir9am  WindDir3pm  ...  Humidity9am  \
0                13           44.0          13          14  ...         71.0   
1                14           44.0           6          15  ...         44.0   
2                15           46.0          13          15  ...         38.0   
3                 4           24.0           9           0  ...         45.0   
4                13           41.0           1           7  ...         82.0   
...             ...            ...         ...         ...  ...          ...   
145455            0           31.0           9           1  ...         51.0   
145456            6           22.0           9           3  ...         56.0   
145457            3           37.0           9          14  ...         53.0   
145458            9           28.0          10           3  ...         51.0   
145459           16           39.0           2           2  ...         62.0   

        Humidity3pm  Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  \
0              22.0       1007.7       1007.1       8.0       7.0     16.9   
1              25.0       1010.6       1007.8       5.0       5.0     17.2   
2              30.0       1007.6       1008.7       5.0       2.0     21.0   
3              16.0       1017.6       1012.8       5.0       5.0     18.1   
4              33.0       1010.8       1006.0       7.0       8.0     17.8   
...             ...          ...          ...       ...       ...      ...   
145455         24.0       1024.6       1020.3       5.0       5.0     10.1   
145456         21.0       1023.5       1019.1       5.0       5.0     10.9   
145457         24.0       1021.0       1016.8       5.0       5.0     12.5   
145458         24.0       1019.4       1016.5       3.0       2.0     15.1   
145459         36.0       1020.2       1017.9       8.0       8.0     15.0   

        Temp3pm  RainToday  RainTomorrow  
0          21.8          0             0  
1          24.3          0             0  
2          23.2          0             0  
3          26.5          0             0  
4          29.7          0             0  
...         ...        ...           ...  
145455     22.4          0             0  
145456     24.5          0             0  
145457     26.1          0             0  
145458     26.0          0             0  
145459     20.9          0             2  

[145460 rows x 22 columns]

In [35]:
Weather.isnull().sum()

Location         0
MinTemp          0
MaxTemp          0
Rainfall         0
Evaporation      0
Sunshine         0
WindGustDir      0
WindGustSpeed    0
WindDir9am       0
WindDir3pm       0
WindSpeed9am     0
WindSpeed3pm     0
Humidity9am      0
Humidity3pm      0
Pressure9am      0
Pressure3pm      0
Cloud9am         0
Cloud3pm         0
Temp9am          0
Temp3pm          0
RainToday        0
RainTomorrow     0
dtype: int64

In [37]:
x = Weather.drop('RainTomorrow', axis=1)
y = Weather['RainTomorrow']

In [39]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.5)

In [41]:
print(x_train.shape, x_test.shape)
print(y_train.shape, y_test.shape)

(72730, 21) (72730, 21)
(72730,) (72730,)


In [43]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [45]:
pred = knn.predict(x_test)
pred

array([0, 0, 0, ..., 0, 0, 1], dtype=int64)

In [47]:
from sklearn.metrics import accuracy_score
KNN = round(accuracy_score(y_test, pred)*100,2)
print(KNN)

82.23


In [49]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()
dtc.fit(x_train, y_train)

DecisionTreeClassifier()

In [51]:
pred1 = dtc.predict(x_test)
pred1

array([1, 0, 0, ..., 0, 1, 1], dtype=int64)

In [53]:
DT = round(accuracy_score(y_test, pred1)*100,2)
print(DT)

76.88


In [55]:
from sklearn.linear_model import LogisticRegression
lgr = LogisticRegression()
lgr.fit(x_train, y_train)

C:\Users\verma\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [56]:
pred2 = lgr.predict(x_test)
pred2

array([0, 0, 0, ..., 0, 0, 1], dtype=int64)

In [57]:
LR = round(accuracy_score(y_test, pred2)*100,2)
print(LR)

81.96


In [58]:
from sklearn.svm import SVC
Svm = SVC()
Svm.fit(x_train, y_train)

SVC()

In [62]:
pred3 = Svm.predict(x_test)
pred3

array([0, 0, 0, ..., 0, 0, 1], dtype=int64)

In [63]:
SVM = round(accuracy_score(y_test, pred3)*100,2)
print(SVM)

81.57


In [64]:
dd = {"KNN": KNN, "Decision Tree": DT, "Logictic Regression": LR}
dd


{'KNN': 82.23, 'Decision Tree': 76.88, 'Logictic Regression': 81.96}

In [65]:
df = pd.DataFrame(dd, index=[0,1,2])
df

KNN  Decision Tree  Logictic Regression
0  82.23          76.88                81.96
1  82.23          76.88                81.96
2  82.23          76.88                81.96